---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: maven-unit-tester-1.0.0
spec:
  description: Test maven application using mvn test command
  params:
    - description: url of source registry image
      name: source-url
      type: string
    - description: sub directory in source to become root dir for build
      name: sub-path
      default: "."
      type: string
    - description: The test command to run in my task
      name: testcmd
      type: string
    - description: The test command to run in my task
      name: workload-name
      type: string
  workspaces:
    - name: shared-data
  # My tasks starts here
  tasks:
    # task 1 pulls the output from source-git-provider and puts it in a workspace called shared-data
    - name: fetch-source
      params:
        - name: url
          value: $(params.source-url)
      taskRef:
        kind: Task
        name: fetch-tgz-content-oci
      workspaces:
        - name: store
          workspace: shared-data

    # task 2 runs the unit tests
    - name: test
      runAfter:
        - fetch-source
      params:
        - name: sub-path
          value: $(params.sub-path)
        - name: testcmd
          value: $(params.testcmd)
        - name: workload-name
          value: $(params.workload-name)
      taskSpec:
        params:
          - name: sub-path
          - name: testcmd
          - name: workload-name
        results:
          - description: Error message if things failed
            name: message
            type: string
        steps:
          - name: test
            image: maven
            env:
              - name: HOME
                value: /tekton/home/
            script: |-
              #!/usr/bin/env sh
              set -eu
              ls -al $(workspaces.store.path)
              cd $(workspaces.store.path)/$(params.sub-path)
              
              set +e
              $(params.testcmd)
              testval=$?
              set -e
              
              if [ $testval -ne 0 ]; then
                echo "Unit tests stage failed. Please run 'tanzu workload logs $(params.workload-name)' to see the run logs for more details." | tee "$(results.message.path)"
                exit $testval
              fi
        stepTemplate:
          computeResources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
      workspaces:
        - name: store
          workspace: shared-data