apiVersion: supplychains.tanzu.vmware.com/v1alpha1
kind: packagedeployv4
metadata:
  name: deploy-tanzu-java-web-app
spec:
  #! The path to the yaml to be applied to the cluster.
  subPath:
    #! The path to the yaml to be applied to the cluster
    #! Required
    path: "packages/tanzu-java-web-app.pve.vmware.com"
  source:
    git:
      branch: "main"
      url: "https://github.com/Mpluya/tap-azure-workload-config-repo.git"
    #! The sub path in the bundle to locate source code
    subPath: "packages/tanzu-java-web-app.pve.vmware.com"
