apiVersion: supplychains.tanzu.vmware.com/v1alpha1
kind: packagedeployv2
metadata:
  name: deploy-tanzu-java-web-app
spec:
  #! The path to the yaml to be applied to the cluster.
  subPath:
    #! The path to the yaml to be applied to the cluster
    #! Required
    path: ""
  source:
    #! Use this object to retrieve source from a git repository.
    #! The tag, commit and branch fields are mutually exclusive, use only one.
    #! Required
    git:
      #! A git branch ref to watch for new source
      branch: ""
      #! A git commit sha to use
      commit: ""
      #! A git tag ref to watch for new source
      tag: ""
      #! The url to the git source repository
      #! Required
      url: ""
    #! The sub path in the bundle to locate source code
    subPath: ""
