apiVersion: supplychains.tanzu.vmware.com/v1alpha1
kind: StatefulSetV1
metadata:
  name: tanzu-java-stateful-app
spec:
  #! Kpack build specification
  build:
    #! Configure workload to use a non-default builder or clusterbuilder
    builder:
      #! builder kind
      kind: "clusterbuilder"
      #! builder name
      name: "default"
    #! cache options
    cache:
      #! whether to use a cache image
      enabled: false
      #! cache image to use
      image: ""
    env:
      #! Required
    - value: ""
      #! Required
      name: ""
    #! Service account to use
    serviceAccountName: "default"
  #! Configuration for the generated Carvel Package
  carvel:
    #! PEM encoded certificate data for the image registry where the files will be pushed to.
    caCertData: ""
    #! Enable the use of IAAS based authentication for imgpkg.
    iaasAuthEnabled:
    #! The domain of the Carvel Package. Combines with spec.carvel.packageName to create the Package refName. If set to "", will use "default.tap".
    packageDomain: ""
    #! The name of the Carvel Package. Combines with spec.carvel.packageDomain to create the Package refName. If set to "", will use the workload name.
    packageName: ""
    #! Service account that gives kapp-controller privileges to create resources in the namespace.
    serviceAccountName: ""
    #! Name of the values Secret that provides customized values to the package installation's templating steps.
    valuesSecretName: ""
  #! May contain an optional array of objects. Each object is a pair of keys: `name` and either `value` or `valueFrom`.
  #! The Conventions component will translate these values into environment variables in the output object.
  env:
    #! The name of the environment variable that will be added to the Pod template spec.
    #! Required
  - name: ""
    #! The literal value of the environment variable.
    #! Note that `value` and `valueFrom` are mutually exclusive; you can only have one per item.
    value: ""
    #! Specifies a non-literal souce for the environment variable's value.
    valueFrom:
      #! Select a value from a `ConfigMap`.
      configMapKeyRef:
        #! Specify whether the ConfigMap or its key must be defined.
        optional:
        #! The key to select.
        key: ""
        #! The name of the referent.
        name: ""
      #! Selects a field of the pod.
      fieldRef:
        #! Path of the field to select in the specified API version.
        fieldPath: ""
        #! Version of the schema the FieldPath is written in terms of.
        apiVersion: ""
      #! Selects a resource of the container.
      resourceFieldRef:
        #! Container name: required for volumes, optional for env vars.
        containerName: ""
        #! Specifies the output format of the exposed resources.
        divisor: ""
        #! Resource to select.
        resource: ""
      #! Selects a key of a secret in the pod's namespace.
      secretKeyRef:
        #! The key of the secret to select from. Must be a valid secret key.
        key: ""
        #! The name of the referent.
        name: ""
        #! Specify whether the Secret or its key must be defined.
        optional:
  gitOps:
    #! the repository to push the pull request to
    #! Required
    url: ""
    #! the branch to commit changes to
    branch: "main"
    #! the relative path within the gitops repository to add the package configuration to.
    subPath: ""
  #! Configuration for the registry to use
  registry:
    #! The name of the repository
    #! Required
    repository: ""
    #! The name of the registry server, e.g. docker.io
    #! Required
    server: ""
  source:
    #! Use this object to retrieve source from a git repository.
    #! The tag, commit and branch fields are mutually exclusive, use only one.
    #! Required
    git:
      #! A git commit sha to use
      commit: ""
      #! A git tag ref to watch for new source
      tag: ""
      #! The url to the git source repository
      #! Required
      url: ""
      #! A git branch ref to watch for new source
      branch: ""
    #! path inside the source to build from (build has no access to paths above the subPath)
    subPath: ""
