apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: appbuildv2
spec:
    defines:
        group: supplychains.tanzu.vmware.com
        kind: appbuildv2
        plural: appbuildv2s
        version: v1alpha1
    description: Supply chain that pulls the source code from Git repository, builds it using buildpacks, scans using trivy, applies convention and packages the output as Carvel package.
    stages:
        - componentRef:
            name: source-git-provider-1.0.0
          name: source-git-provider
        - componentRef:
            name: buildpack-build-1.0.0
          name: buildpack-build
        - componentRef:
            name: trivy-image-scan-1.0.0
          name: trivy-image-scan
        - componentRef:
            name: conventions-1.0.0
          name: conventions
        - componentRef:
            name: app-config-web-1.0.0
          name: app-config-web
        - componentRef:
            name: carvel-package-1.0.0
          name: carvel-package
